version: '3.8'

services:
  pgsqldb:
    image: postgres:13.4
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'admin'
    ports:
      - 5432:5432
    volumes:
      - pgsqldata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - pgsqldb

volumes:
  pgsqldata: null

